name: Deploy web services to Google App Engine

on:
  # Push to 'release' branch
  # push:
  #   branches:
  #     - release
  # Closed pull reuqest on 'main' branch
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    paths:
      - article-service/**

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./article-service

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml --quiet
        working-directory: ./article-service
